query HomePage {
  nodeByUri(uri: "home") {
    __typename
    ... on Page {
      id
      title
      home {
        pageTitle
        content {
          title
          link {
            title
            url
          }
          intro
          content
          image {
            altText
            srcSet
            mediaDetails {
              height
              width
            }
          }
        }
      }
    }
  }
}
