query MenusAll {
  menus {
    nodes {
      id
      databaseId
      name
      menuItems {
        edges {
          node {
            id
            label
            target
            uri
          }
        }
      }
    }
  }
}
