query PostList($limit: Int = 1000) {
  posts(first: $limit) {
    nodes {
      title
      slug
      featuredImage {
        node {
          altText
          srcSet
          sourceUrl
          sizes
          mediaDetails {
            height
            width
          }
        }
      }
    }
  }
}
