query SiteSettings {
  generalSettings {
    title
    description
  }
  siteSettings {
    siteSettings {
      socialLinks {
        links {
          target
          title
          url
        }
      }
    }
  }
}
